on:
  push:
    tags:
    - '*'
    - '!*.x'

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows
    steps:
    - uses: actions/checkout@v2
    - name: Get Current Release Version
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: Release v${{ steps.get_version.outputs.VERSION }}
        body: |
          GOG Release v${{ steps.get_version.outputs.VERSION }}
          
          For full change details read the [CHANGELOG](/CHANGELOG.md)
    - uses: wangyoucao577/go-release-action@v1.26
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        asset_name: GOG-${{ steps.get_version.outputs.VERSION }}-${{ matrix.goos }}-${{ matrix.goarch }}
        binary_name: gog
        ldflags: "-X 'sykesdev.ca/gog/update.Version=${{ steps.get_version.outputs.VERSION }}'"
        extra_files: LICENSE README.md CHANGELOG.md